vars:
  - paths:
      mount_point_data : ./
stages:
  get_patterns_along_traj:
    cmd: python get_patterns_along_traj.py
    wdir: analysis
    deps:
    - ../data/ERA5/trajectories/Trajectories_back_ClassificationCenters_IR.nc
    - ../data/SGFF/Daily_1x1_MODIS-IR_NorthAtlantic_SGFF.nc
    - ../data/MCC/Daily_1x1_MODIS_C6_MCC_2018.nc
    - ../data/MEASURES/Daily_1x1_MEASURES_CLASS_2018.nc
    outs:
    - ../data/result/patterns_along_trajectories_MCC.pq
    - ../data/result/patterns_along_trajectories_SGFF.pq
    - ../data/result/patterns_along_trajectories_MEASURES.pq
  plot_patterns_along_traj_all_datasets:
    cmd: python patterns_along_trajectory_alldatasets.py
    wdir: analysis
    deps:
    - ../data/ERA5/trajectories/Trajectories_back_ClassificationCenters_IR.nc
    - ../data/result/patterns_along_trajectories_MCC.pq
    - ../data/result/patterns_along_trajectories_SGFF.pq
    - ../data/result/patterns_along_trajectories_MEASURES.pq
    outs:
    - ../figures/patterns_along_trajectory_SGFF.pdf
    - ../figures/patterns_along_trajectory_MEASURES.pdf
    - ../figures/patterns_along_trajectory_MCC.pdf
  plot_patterns_along_traj_SGFF:
    cmd: python patterns_along_trajectory.py
    wdir: analysis
    deps:
    - ../data/ERA5/trajectories/Trajectories_back_ClassificationCenters_IR.nc
    - ../data/result/patterns_along_trajectories_SGFF.pq
    outs:
    - ../figures/patterns_along_trajectory_SGFF_allTimes.pdf
  download_MODIS_IO:
    cmd: bash run_download_MODIS.sh ../../setups/IndianOcean.yaml
    wdir: data/MODIS
    outs:
    - ${paths.mount_point_data}/data/MODIS/Aqua_MODIS_IR/IndianOcean
  classify_MODIS_IO:
    cmd: bash data/MODIS/run_classification_world.sh setups/IndianOcean.yaml
    outs:
    - ${paths.mount_point_data}/data/SGFF/level0/IO/
  download_MODIS_TB1:
    cmd: bash data/MODIS/run_download_MODIS.sh setups/TropicalBelt1.yaml
    deps:
    - setups/TropicalBelt1.yaml
    outs:
    - ${paths.mount_point_data}/data/MODIS/Aqua_MODIS_IR/TropicalBelt1:
        cache: false
        persist: true
    frozen: true
  download_MODIS_TB2:
    cmd: bash data/MODIS/run_download_MODIS.sh setups/TropicalBelt2.yaml
    deps:
    - setups/TropicalBelt2.yaml
    outs:
    - ${paths.mount_point_data}/data/MODIS/Aqua_MODIS_IR/TropicalBelt2:
        cache: false
        persist: true
    frozen: true
  download_MODIS_TB3:
    cmd: bash data/MODIS/run_download_MODIS.sh setups/TropicalBelt3.yaml
    deps:
    - setups/TropicalBelt3.yaml
    outs:
    - ${paths.mount_point_data}/data/MODIS/Aqua_MODIS_IR/TropicalBelt3:
        cache: false
        persist: true
    frozen: true
  download_MODIS_TB4:
    cmd: bash data/MODIS/run_download_MODIS.sh setups/TropicalBelt4.yaml
    deps:
    - setups/TropicalBelt4.yaml
    outs:
    - ${paths.mount_point_data}/data/MODIS/Aqua_MODIS_IR/TropicalBelt4:
        cache: false
        persist: true
    frozen: true
  download_MODIS_TB5:
    cmd: bash data/MODIS/run_download_MODIS.sh setups/TropicalBelt5.yaml
    deps:
    - setups/TropicalBelt5.yaml
    outs:
    - ${paths.mount_point_data}/data/MODIS/Aqua_MODIS_IR/TropicalBelt5:
        cache: false
        persist: true
    frozen: true
  download_MODIS_TB6:
    cmd: bash data/MODIS/run_download_MODIS.sh setups/TropicalBelt6.yaml
    deps:
    - setups/TropicalBelt6.yaml
    outs:
    - ${paths.mount_point_data}/data/MODIS/Aqua_MODIS_IR/TropicalBelt6:
        cache: false
        persist: true
    frozen: true
  download_MODIS_TB:
    cmd: echo "Download all MODIS Tropical Belt images"
    deps:
    - ${paths.mount_point_data}/data/MODIS/Aqua_MODIS_IR/TropicalBelt1
    - ${paths.mount_point_data}/data/MODIS/Aqua_MODIS_IR/TropicalBelt2
    - ${paths.mount_point_data}/data/MODIS/Aqua_MODIS_IR/TropicalBelt3
    - ${paths.mount_point_data}/data/MODIS/Aqua_MODIS_IR/TropicalBelt4
    - ${paths.mount_point_data}/data/MODIS/Aqua_MODIS_IR/TropicalBelt5
    - ${paths.mount_point_data}/data/MODIS/Aqua_MODIS_IR/TropicalBelt6
    frozen : true
  stitch_images_BT:
    cmd: bash data/MODIS/stitch_images.sh ${paths.mount_point_data}/data/MODIS/Aqua_MODIS_IR/TropicalBelt1/
      ${paths.mount_point_data}/data/MODIS/Aqua_MODIS_IR/TropicalBelt2/ ${paths.mount_point_data}/data/MODIS/Aqua_MODIS_IR/TropicalBelt3/
      ${paths.mount_point_data}/data/MODIS/Aqua_MODIS_IR/TropicalBelt4/ ${paths.mount_point_data}/data/MODIS/Aqua_MODIS_IR/TropicalBelt5/
      ${paths.mount_point_data}/data/MODIS/Aqua_MODIS_IR/TropicalBelt6/
    deps:
    - ${paths.mount_point_data}/data/MODIS/Aqua_MODIS_IR/TropicalBelt1
    - ${paths.mount_point_data}/data/MODIS/Aqua_MODIS_IR/TropicalBelt2
    - ${paths.mount_point_data}/data/MODIS/Aqua_MODIS_IR/TropicalBelt3
    - ${paths.mount_point_data}/data/MODIS/Aqua_MODIS_IR/TropicalBelt4
    - ${paths.mount_point_data}/data/MODIS/Aqua_MODIS_IR/TropicalBelt5
    - ${paths.mount_point_data}/data/MODIS/Aqua_MODIS_IR/TropicalBelt6
    outs:
    - ${paths.mount_point_data}/data/MODIS/Aqua_MODIS_IR/TropicalBelt:
        cache: false
    frozen: true
  classify_MODIS_TB:
    cmd: bash ./data/MODIS/run_classification_world.sh setups/TropicalBelt.yaml
    wdir: ./
    vars:
    - setups/TropicalBelt.yaml
    outs:
    - ${datastore}/data/SGFF/level0/TB/:
        persist: true
  create_mask_TB:
    cmd: python src/helpers/convert_pkl_to_zarr.py setups/TropicalBelt.yaml
    wdir: ./
    vars:
    - setups/TropicalBelt.yaml
    outs:
    - ${classification.output_zarr}/time
    - ${classification.output_zarr}/latitude
    - ${classification.output_zarr}/longitude
    - ${classification.output_zarr}/pattern
    - ${classification.output_zarr}/mask
    - ${classification.output_pkl_joint}
    deps:
    - ${datastore}/data/SGFF/level0/TB
  mask_classifications:
    cmd: python data/MODIS/mask_footprint.py setups/TropicalBelt.yaml
    vars:
    - setups/TropicalBelt.yaml
    deps:
    - data/MODIS/mask_footprint.py
    - ${classification.output_zarr}/time
    - ${classification.output_zarr}/latitude
    - ${classification.output_zarr}/longitude
    - ${classification.output_zarr}/pattern
    - ${classification.output_zarr}/mask
    - ${classification.output_zarr}/.zmetadata
    - ${classification.output_zarr}/.zgroup
    - ${classification.output_zarr}/.zattrs
    outs:
    - ${classification.output_zarr}/sat_mask:
        cache: false
    - ${classification.output_zarr}/sat_bt:
        cache: false
  grid_mask_TB:
    cmd: python analysis/prepare_data_grid.py setups/TropicalBelt.yaml
    wdir: ./
    vars:
    - setups/TropicalBelt.yaml
    outs:
    - data/SGFF/level2/TB/
    deps:
    - ${classification.output_zarr}
