stages:
  get_patterns_along_traj:
    cmd: python get_patterns_along_traj.py
    wdir: analysis
    deps:
    - ../data/ERA5/trajectories/Trajectories_back_ClassificationCenters_IR.nc
    - ../data/SGFF/Daily_1x1_MODIS-IR_NorthAtlantic_SGFF.nc
    - ../data/MCC/Daily_1x1_MODIS_C6_MCC_2018.nc
    - ../data/MEASURES/Daily_1x1_MEASURES_CLASS_2018.nc
    outs:
    - ../data/result/patterns_along_trajectories_MCC.pq
    - ../data/result/patterns_along_trajectories_SGFF.pq
    - ../data/result/patterns_along_trajectories_MEASURES.pq
  plot_patterns_along_traj_all_datasets:
    cmd: python patterns_along_trajectory_alldatasets.py
    wdir: analysis
    deps:
    - ../data/ERA5/trajectories/Trajectories_back_ClassificationCenters_IR.nc
    - ../data/result/patterns_along_trajectories_MCC.pq
    - ../data/result/patterns_along_trajectories_SGFF.pq
    - ../data/result/patterns_along_trajectories_MEASURES.pq
    outs:
    - ../figures/patterns_along_trajectory_SGFF.pdf
    - ../figures/patterns_along_trajectory_MEASURES.pdf
    - ../figures/patterns_along_trajectory_MCC.pdf
  plot_patterns_along_traj_SGFF:
    cmd: python patterns_along_trajectory.py
    wdir: analysis
    deps:
    - ../data/ERA5/trajectories/Trajectories_back_ClassificationCenters_IR.nc
    - ../data/result/patterns_along_trajectories_SGFF.pq
    outs:
    - ../figures/patterns_along_trajectory_SGFF_allTimes.pdf
  download_MODIS_IO:
    cmd: bash run_download_MODIS.sh ../../setups/IndianOcean.yaml
    wdir: data/MODIS
    outs:
    - /mount/sgff/nfs/data/MODIS/Aqua_MODIS_IR/IndianOcean
  classify_MODIS_IO:
    cmd: bash run_classification_world.sh ../../setups/IndianOcean.yaml
    wdir: data/MODIS
    outs:
    - /mount/sgff/nfs/data/SGFF/level0/
  download_MODIS_TB1:
    cmd: bash run_download_MODIS.sh ../../setups/TropicalBelt1.yaml
    wdir: data/MODIS
    outs:
    - /mount/sgff/nfs/data/MODIS/Aqua_MODIS_IR/TropicalBelt1
  download_MODIS_TB2:
    cmd: bash run_download_MODIS.sh ../../setups/TropicalBelt2.yaml
    wdir: data/MODIS
    outs:
    - /mount/sgff/nfs/data/MODIS/Aqua_MODIS_IR/TropicalBelt2:
        cache: false
#  classify_MODIS_TB:
#    cmd: bash run_classification_world.sh ../../setups/TropicalBelt.yaml
#    wdir: data/MODIS
#    outs:
#    - /mount/sgff/nfs/data/SGFF/level0/
