name: schulz_et_al_2023
channels:
  - conda-forge
  - observingClouds
dependencies:
  - python>=3.9
  - omegaconf
  - ca-certificates
  - openssl
  - ipykernel
  - zarr
  - dask
  - tqdm
  - dask-jobqueue>=0.7.4
  - nodejs
  - jupyter
  - jupyterlab
  - dask-labextension
  - certifi
  - distributed
  - netcdf4
  - intake<2.0.0
  - matplotlib
  - dvc
  - hvplot
  - datashader>=0.13.0
  - cmcrameri
  - haversine
  - seaborn
  - go
  - nc-time-axis
  - pydap
  - metpy
  - python-graphviz
  - netcdf-fortran
  - fftw
  - filelock
  - pyarrow
  - pytables
  - conda-build
  - pint-xarray
  - pytest
  - black
  - xarray-datatree>=0.0.10
  - flox
  - xarray>=2022.10.0
  - cartopy
  - fire
  - cfgrib
  - tree
  - pandas>=1.5.1
  - mpld3
  - ipdb
  - ffmpeg
  - anaconda-client
  - satdownload
  - dvc-webdav
  - selenium
  - firefox
  - geckodriver
  - pip
  - pip:
    - opencv-python
